service: inference

frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage}
  region: ca-central-1
  lambdaHashingVersion: 20201221
  memorySize: 512
  timeout: 30
  apiName: ${self:service}-${opt:stage}
  apiGateway:
    description: REST API ${self:service}
    metrics: true

functions: ${file(functions.yml):functions}
